baseURL: "/"
title: "mjindra.eu"
theme: "PaperMod"
paginate: 4

buildDrafts: false
buildExpired: false
enableRobotsTXT: true

languageCode: "en"
relativeURLs: false
enableEmoji: true
defaultContentLanguage: de

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  en:
    languageName: "English"
    profileMode:
      enabled: true
      title: "Welcome strange visitor"
      imageUrl: img/profile.png
      buttons:
      - name: about
        url: about
    menu:
      main:
      - name: about
        url: about
        weight: 1
      - name: blog
        url: posts
        weight: 2
      - name: projects
        url: projects
        weight: 3
      - name: 📁
        url: archives
        weight: 4
      - name: 🔎
        url: search
        weight: 5

  de:
    languageName: "English"
    profileMode:
      enabled: true
      title: "Willkommen, Fremder"
      imageUrl: img/profile.png
      buttons:
      - name: Über
        url: about
    menu:
      main:
      - name: Über
        url: about
        weight: 1
      - name: Blog
        url: posts
        weight: 2
      - name: Projekte
        url: projects
        weight: 3
      - name: 📁
        url: archives
        weight: 4
      - name: 🔎
        url: search
        weight: 5

params:
  env: production

  # settings
  DateFormat: ":date_long"
  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowToc: false
  comments: false
  ShowCodeCopyButtons: true

  assets:
    # favicon
    favicon: favicon/logo_mjindra.eu_64x64.png
    favicon16x16: favicon/logo_mjindra.eu_16x16.png
    favicon32x32: favicon/logo_mjindra.eu_32x32.png
    apple_touch_icon: favicon/logo_mjindra.eu_apple-touch-icon.png

  # social links
  socialIcons:
    - name: Email
      url: "mailto:martin@mjindra.eu"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/martinjindra"
    - name: Instagram
      url: "https://www.instagram.com/mjindra_eu"
    - name: Gitlab
      url: "https://gitlab.com/MartinJindra/"
    - name: RSS
      url: "index.xml"
