baseURL: "/"
title: "derchef"
theme: "PaperMod"

buildDrafts: false
buildExpired: false

languageCode: "en"
relativeURLs: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
      - name: about
        url: about
        weight: 5
      - name: projects
        url: projects
        weight: 5
      - name: blog
        url: blog
        weight: 5

params:

  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowToc: true

  profileMode:
    enabled: true
    title: "Welcome strange visitor"
    imageUrl: img/profile.png
    buttons:
    - name: about
      url: about

  socialIcons:
    - name: Github
      url: "https://github.com/MartinJindra"
    - name: Gitea
      url: "https://git.derchef.site/derchef"
    - name: RSS
      url: "index.xml"
