baseURL: "/"
title: "mjindra.eu"
theme: "PaperMod"
paginate: 4

buildDrafts: false
buildExpired: false
enableRobotsTXT: true

languageCode: "en"
relativeURLs: true
enableEmoji: true
defaultContentLanguage: de

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  en:
    languageName: "English"
    profileMode:
      enabled: true
      title: "Welcome strange visitor"
      imageUrl: img/profile.png
      buttons:
      - name: about
        url: about
    menu:
      main:
      - name: 🔎
        url: search
      - name: about
        url: about
        weight: 5
      - name: projects
        url: projects
        weight: 5
      - name: blog
        url: blog
        weight: 5
    editPost:
      URL: "https://github.com/MartinJindra/mjindra.eu/tree/main/content"
      Text: "Suggest Changes"
      appendFilePath: true

  de:
    languageName: "English"
    profileMode:
      enabled: true
      title: "Willkommen, Fremder"
      imageUrl: img/profile.png
      buttons:
      - name: Über
        url: about
    menu:
      main:
      - name: 🔎
        url: search
      - name: Über
        url: about
        weight: 5
      - name: Projekte
        url: projects
        weight: 5
      - name: Blog
        url: blog
        weight: 5
    editPost:
      URL: "https://github.com/MartinJindra/mjindra.eu/tree/main/content"
      Text: "Änderungen vorschlagen"
      appendFilePath: true

params:
  env: production

  # settings
  DateFormat: ":date_long"
  defaultTheme: auto
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowToc: false
  comments: false

  # favicon
  assets:
    favicon: favicon/logo_mjindra.eu_64x64.png
    favicon16x16: favicon/logo_mjindra.eu_16x16.png
    favicon32x32: favicon/logo_mjindra.eu_32x32.png
    apple_touch_icon: favicon/logo_mjindra.eu_apple-touch-icon.png

  # social links
  socialIcons:
    - name: Email
      url: "mailto:martin@mjindra.eu"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/martinjindra"
    - name: Instagram
      url: "https://www.instagram.com/mjindra_eu"
    - name: Github
      url: "https://github.com/MartinJindra"
    # - name: Gitlab
    #   url: "https://gitlab.com/derchef"
    # - name: Gitea
    #   url: "https://git.mjindra.eu/derchef"
    # - name: RSS
    #   url: "index.xml"
