baseURL: "https://derchef.site/"
title: "derchef"
theme: "PaperMod"

buildDrafts: false
buildExpired: false

languageCode: "en"
relativeURLs: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
      - name: About
        url: about
        weight: 5
      - name: Projects
        url: projects
        weight: 5
      - name: Blog
        url: blog
        weight: 5

params:

  defaultTheme: dark
  disableThemeToggle: false

  profileMode:
    enabled: true
    title: "Welcome strange visitor"

  socialIcons:
    - name: "Github"
      url: "https://github.com/MartinJindra"
    - name: "Gitlab"
      url: "https://gitlab.com/derchef"
    - name: "Gitea"
      url: "https://git.derchef.site/derchef"
    - name: RSS
      url: "index.xml"
