baseURL: "/"
title: "mjindra.eu"
theme: "PaperMod"
paginate: 4

buildDrafts: false
buildExpired: false
enableRobotsTXT: true

languageCode: "en"
relativeURLs: false
enableEmoji: true
defaultContentLanguage: de

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production

  # settings
  DateFormat: ":date_long"
  defaultTheme: auto
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowToc: false
  comments: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: true

  profileMode:
    enabled: true
    title: "Site is under maintenance"
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size

  assets:
    favicon16x16: favicon/logo_mjindra.eu_16x16.png
    favicon32x32: favicon/logo_mjindra.eu_32x32.png
    favicon: favicon/logo_mjindra.eu_64x64.png
    apple_touch_icon: favicon/logo_mjindra.eu_apple-touch-icon.png
