baseURL: "/"
title: "derchef"
theme: "PaperMod"

buildDrafts: false
buildExpired: false

languageCode: "en"
relativeURLs: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
      - name: about
        url: about
        weight: 5
      - name: projects
        url: projects
        weight: 5
      - name: blog
        url: blog
        weight: 5

params:

  editPost:
    URL: "https://github.com/MartinJindra/derchef.site/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # settings
  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowToc: true

  # favicon
  assets:
    favicon: favicon/logo_derchef.site_64x64.png
    favicon16x16: favicon/logo_derchef.site_16x16.png
    favicon32x32: favicon/logo_derchef.site_32x32.png
    apple_touch_icon: favicon/logo_derchef.site_apple-touch-icon.png

  # homepage mode
  profileMode:
    enabled: true
    title: "Welcome strange visitor"
    imageUrl: img/profile.png
    buttons:
    - name: about
      url: about

  # social links
  socialIcons:
    - name: LinkedIn
      url: "https://www.linkedin.com/in/martinjindra"
    - name: Github
      url: "https://github.com/MartinJindra"
    - name: Gitea
      url: "https://git.derchef.site/derchef"
    - name: RSS
      url: "index.xml"

