baseURL: "https://derchef.site/"
title: "derchef"
theme: "PaperMod"

buildDrafts: false
buildExpired: false

languageCode: "en"
relativeURLs: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
      - name: Services
        url: services
        weight: 5
      - name: Blog
        url: blog
        weight: 5
      - name: Contact
        url: contact
        weight: 5

params:

  defaultTheme: dark
  disableThemeToggle: false

  profileMode:
    enabled: true
    title: "Welcome"
    imageUrl: "https://git.derchef.site/assets/img/logo.svg"
    imageWidth: 240
    buttons:
    - name: CV
      url: "https://git.derchef.site/derchef/derchef_cv/raw/branch/main/CV_Martin_Jindra.pdf"
    #Content: >
    #   Homepage of a student, programmer and service administrator.
    #   - [soure code](https://git.derchef.site/derchef/derchef.site)
    #   - links:
  socialIcons:
    - name: "Github"
      url: "https://github.com/MartinJindra"
    - name: "Gitlab"
      url: "https://gitlab.com/derchef"
    - name: "Gitea"
      url: "https://git.derchef.site/derchef"

