baseURL: "https://derchef.site/"
title: "derchef"
theme: "PaperMod"

buildDrafts: false
buildExpired: false

languageCode: "en"
relativeURLs: true

params:
  homeInfoParams:
    Title: "derChef.site"
    Content: >
      Welcome to the homepage of the derchef
      
      - Sourecode of this site [link](https://git.derchef.site/derchef/derchef.site)
