baseURL: "/"
title: "derchef"
theme: "PaperMod"
paginate: 4

buildDrafts: false
buildExpired: false

languageCode: "en"
relativeURLs: true
enableEmoji: true
defaultContentLanguage: de

languages:
  en:
    languageName: "English"
    profileMode:
      enabled: true
      title: "Welcome strange visitor"
      imageUrl: img/profile.png
      buttons:
      - name: about
        url: about
    menu:
      main:
      - name: about
        url: about
        weight: 5
      - name: projects
        url: projects
        weight: 5
      - name: blog
        url: blog
        weight: 5
    editPost:
      URL: "https://github.com/MartinJindra/derchef.site/tree/main/content"
      Text: "Suggest Changes" # edit text
      appendFilePath: true # to append file path to Edit link
    
  de:
    languageName: "English"
    title: "derchef"
    profileMode:
      enabled: true
      title: "Willkommen, Fremder"
      imageUrl: img/profile.png
      buttons:
      - name: Über
        url: about
    menu:
      main:
      - name: Über
        url: about
        weight: 5
      - name: Projekte
        url: projects
        weight: 5
      - name: Blog
        url: blog
        weight: 5
    editPost:
      URL: "https://github.com/MartinJindra/derchef.site/tree/main/content"
      Text: "Änderungen vorschlagen" # edit text
      appendFilePath: true # to append file path to Edit link

params:
  env: production

  # settings
  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowToc: true
  DateFormat: ":date_long"

  # favicon
  assets:
    favicon: favicon/logo_derchef.site_64x64.png
    favicon16x16: favicon/logo_derchef.site_16x16.png
    favicon32x32: favicon/logo_derchef.site_32x32.png
    apple_touch_icon: favicon/logo_derchef.site_apple-touch-icon.png

  # social links
  socialIcons:
    - name: LinkedIn
      url: "https://www.linkedin.com/in/martinjindra"
    - name: Github
      url: "https://github.com/MartinJindra"
    - name: Gitea
      url: "https://git.derchef.site/derchef"
    - name: RSS
      url: "index.xml"
