baseURL: "https://box.derchef.email/"
title: "derchef"
theme: "PaperMod"

languageCode: "en"
relativeURLs: true

params:
  homeInfoParams:
    Title: "derChef.site"
    Content: >
      Welcome to derChefs homepage
