version: "3"
services:
  server:
    image: caddy:alpine
    container_name: "server_mjindra.eu"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public/:/usr/share/caddy/:ro
