version: "3"

services:
  caddy:
    image: caddy:alpine
    container_name: "caddy"
    restart: always
    ports:
      - "80:80"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile:ro
      - $PWD/public/:/usr/share/caddy/:ro
